snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: accenture

      # User/password auth
      user: vrathore
      password: JaiMahakal@1

      role: PUBLIC
      database: TEST_DB
      warehouse: TEST_DW
      schema: DB_CORE_DEV
      threads: 2
      client_session_keep_alive: False
      #query_tag: "SF_QUERY"

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)